#!/usr/bin/env python3
import os.path
import sys, zipfile

def countTextFiles(dirName):
  pg = 1
  while True:
    fileName = "{:03d}.txt".format(pg)
    fileName = os.path.join(dirName, fileName)
    if not os.path.exists(fileName):
      pg -= 1
      break
    pg += 1
  return pg

def pageFiles(dirName, pageCount):
  res = dict()
  noPageFiles = list()
  patterns = dict()
  for i in range(pageCount):
    patterns["{:03d}".format(i+1)] = True
  for fileName in os.listdir(dirName):
    name, ext = os.path.splitext(fileName)
    if name in patterns:
      val = res.setdefault(name, list())
      val.append(fileName)
      res[name] = val
    else:
      noPageFiles.append(fileName)
  return res, noPageFiles

def zipFiles(prefix, part, dirName, files):
  zipName = "{}-{:02d}.zip".format(prefix, part)
  zf = zipfile.ZipFile(zipName, 'w', zipfile.ZIP_DEFLATED, True)
  for f in files:
    fileName = os.path.join(dirName, f)
    zf.write(fileName, f)
  zf.close()
  
def zipRange(prefix, dirName, size, pageFiles, extraFiles):
  part = 0
  files = list(extraFiles)
  count = len(pageFiles)
  for i in range(1, count+1):
    baseName = "{:03d}".format(i)
    for f in pageFiles[baseName]:
      files.append(f)
    if i % size == 0:
      part += 1
      zipFiles(prefix, part, dirName, files)
      files.clear()
  if count % size != 0:
    part += 1   
    zipFiles(prefix, part, dirName, files)

def split(prefix, dirName, size):
  count = countTextFiles(dirName)
  pages, extras = pageFiles(dirName, count)
  zipRange(prefix, dirName, size, pages, extras)

def usage(cmd):
  print("Usage: {} zipPrefix uploadDir chunkSize".format(cmd))

if __name__ == '__main__':
  if len(sys.argv) != 4:
    usage(sys.argv[0])
    sys.exit(1)
  else:
    split(sys.argv[1], sys.argv[2], int(sys.argv[3]))
